// Generated by CoffeeScript 1.6.3
(function() {
  var Promise, connectionWrapper, mysql;

  mysql = require('mysql');

  Promise = require('bluebird');

  connectionWrapper = function(connection, poolCluster) {
    var db;
    return db = {
      query: function(sql, values) {
        return (Promise.promisify(connection.query, connection))(sql, values);
      },
      begin: function(callback) {
        var self, transaction, transactionDeferred;
        self = this;
        transactionDeferred = Promise.defer();
        transaction = {};
        transaction.rollback = function() {
          this.rolledback = true;
          transactionDeferred.reject();
          return connection.rollback(function() {});
        };
        transaction.commit = function() {
          if (!this.rolledback) {
            return connection.commit((function(_this) {
              return function(err) {
                if (err) {
                  _this.rollback();
                  throw err;
                } else {
                  return transactionDeferred.resolve(true);
                }
              };
            })(this));
          }
        };
        transaction.query = function(sql, values) {
          return self.query(sql, values)["catch"]((function(_this) {
            return function(err) {
              _this.rollback();
              return console.log('Begin query error', err.message);
            };
          })(this));
        };
        connection.beginTransaction(function(err) {
          transaction.callback = callback;
          return transaction.callback();
        });
        return transactionDeferred.promise;
      },
      end: function() {
        return poolCluster.end();
      }
    };
  };

  module.exports = {
    config: function(config) {
      var configuration, group, _results;
      this._poolCluster = mysql.createPoolCluster({
        canRetry: true,
        removeNodeErrorCount: 2,
        defaultSelector: 'RR'
      });
      _results = [];
      for (group in config) {
        configuration = config[group];
        _results.push(this._poolCluster.add(group, configuration));
      }
      return _results;
    },
    connect: function(group) {
      var getConnection, pool;
      if (group === 'slave') {
        pool = this._poolCluster.of(group.toLowerCase() + '*');
        getConnection = Promise.promisify(pool.getConnection, pool);
        return getConnection().then((function(_this) {
          return function(connection) {
            return connectionWrapper(connection, _this._poolCluster);
          };
        })(this));
      } else {
        getConnection = Promise.promisify(this._poolCluster.getConnection, this._poolCluster);
        return getConnection(group.toLowerCase()).then((function(_this) {
          return function(connection) {
            return connectionWrapper(connection, _this._poolCluster);
          };
        })(this));
      }
    }
  };

}).call(this);
